const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../core.js');
const fixture=()=>{const d=C.empty();d.students.push({id:'student1',name:'테스트수련생',group:'초등부',fee:150000,memo:'',guardian:'',phone:'',joined:'2026-01-01',status:'active',schedule:[1,2,3,4,5]});return d;};
test('clean backup round trip',()=>assert.deepEqual(C.validate(JSON.parse(JSON.stringify(fixture()))),fixture()));
test('attendance updates rather than duplicates',()=>{const d=fixture();C.mark(d,'student1','2026-09-01','present');C.mark(d,'student1','2026-09-01','late');assert.equal(d.attendance.length,1);assert.equal(d.attendance[0].status,'late');});
test('future attendance refused',()=>assert.throws(()=>C.mark(fixture(),'student1','2099-01-01','present')));
test('attendance before enrollment refused',()=>assert.throws(()=>C.mark(fixture(),'student1','2025-01-01','present')));
test('unknown student refused',()=>assert.throws(()=>C.mark(fixture(),'unknown','2026-09-01','present')));
test('unmarked is not an absence or long absence',()=>{const d=fixture();assert.equal(C.report(d,'day','2026-09-01').rate,null);assert.deepEqual(C.absences(d,'2026-09-20'),[]);});
test('long absence requires explicit absent entry',()=>{const d=fixture();C.mark(d,'student1','2026-09-01','present');C.mark(d,'student1','2026-09-02','absent');assert.equal(C.absences(d,'2026-09-09').length,1);C.mark(d,'student1','2026-09-08','excused');assert.equal(C.absences(d,'2026-09-09').length,0);});
test('paused students excluded from absence and class eligibility',()=>{const d=fixture();d.students[0].status='paused';C.mark(d,'student1','2026-09-02','absent');assert.equal(C.absences(d,'2026-09-20').length,0);assert.equal(C.eligible(d.students[0],'2026-09-21'),false);});
test('attendance rate excludes excused and includes late',()=>{const d=fixture();for(const [date,status] of [['01','present'],['02','late'],['03','absent'],['04','excused']])C.mark(d,'student1','2026-09-'+date,status);const r=C.report(d,'month','2026-09-20');assert.equal(r.rate,67);assert.equal(r.checked,3);});
test('Monday week and leap-year month boundaries',()=>{assert.deepEqual(C.period('week','2026-09-27'),['2026-09-21','2026-09-27']);assert.deepEqual(C.period('month','2024-02-10'),['2024-02-01','2024-02-29']);assert.deepEqual(C.period('month','2026-12-15'),['2026-12-01','2026-12-31']);});
test('ambiguous names do not trigger write command',()=>{const d=fixture();d.students.push({...d.students[0],id:'student2'});assert.equal(C.command(d,'테스트수련생 출석 처리').type,'answer');});
test('natural language write identifies explicit name and today',()=>{const r=C.command(fixture(),'테스트수련생 출석 처리','2026-09-01');assert.deepEqual(r,{type:'mark',studentId:'student1',date:'2026-09-01',status:'present'});});
test('sending and payment instructions blocked',()=>{for(const q of ['문자 발송','결제 실행','수련생 삭제'])assert.equal(C.command(fixture(),q).type,'answer');});
test('duplicate attendance restore rejected',()=>{const d=fixture();C.mark(d,'student1','2026-09-01','present');d.attendance.push({...d.attendance[0],id:'other'});assert.throws(()=>C.validate(d));});
test('duplicate monthly bill and overpayment rejected',()=>{const d=fixture();const p={id:'p1',studentId:'student1',month:'2026-09',due:150000,paid:50000,paidAt:'2026-09-01',note:''};d.payments.push(p);assert.equal(C.report(d,'month','2026-09-01').paid,50000);d.payments.push({...p,id:'p2'});assert.throws(()=>C.validate(d));d.payments.pop();p.paid=200000;assert.throws(()=>C.validate(d));});
test('malformed and dangerous backup payloads rejected',()=>{for(const change of [d=>d.version=2,d=>d.students[0].id='\" onclick=evil',d=>d.students[0].fee=-1,d=>d.students[0].schedule=[],d=>d.settings.absenceDays=0,d=>d.attendance.push({id:'a1',studentId:'ghost',date:'2026-09-01',status:'present'})]){const d=fixture();change(d);assert.throws(()=>C.validate(d));}});
test('invalid date rejected',()=>{assert.equal(C.validDate('2026-02-30'),false);assert.equal(C.validDate('2026-13-01'),false);assert.throws(()=>C.period('week','bad'));});
test('draft remains draft after backup restore',()=>{const d=fixture();d.drafts.push({id:'m1',studentId:'student1',text:'안부 초안',kind:'결석 안부',created:'2026-09-01',status:'draft'});assert.equal(C.validate(d).drafts[0].status,'draft');d.drafts[0].status='sent';assert.throws(()=>C.validate(d));});
test('class schedule and enrollment respected',()=>{const s=fixture().students[0];assert.equal(C.eligible(s,'2026-09-21'),true);assert.equal(C.eligible(s,'2026-09-27'),false);assert.equal(C.eligible(s,'2025-12-31'),false);});
