const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const base=path.join(__dirname,'..');
function boot(raw){
 const dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'http://localhost/dojang-os/',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window;w.structuredClone=structuredClone;w.confirm=()=>true;w.crypto.randomUUID=()=>require('node:crypto').randomUUID();w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 if(raw)w.localStorage.setItem('dojang-os:v1',raw);
 w.eval(fs.readFileSync(path.join(base,'core.js'),'utf8'));w.eval(fs.readFileSync(path.join(base,'app.js'),'utf8'));
 const $=s=>w.document.querySelector(s),click=s=>{assert.ok($(s),s);$(s).click();},set=(s,value)=>{$(s).value=value;},submit=s=>$(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})),change=(s,value)=>{set(s,value);$(s).dispatchEvent(new w.Event('change',{bubbles:true}));},state=()=>JSON.parse(w.localStorage.getItem('dojang-os:v1'));
 function student(name='가상수련생'){click('#addStudentBtn');set('[name="name"]',name);set('[name="joined"]','2026-01-01');submit('#studentForm');}
 return {w,$,click,set,submit,change,state,student,close:()=>dom.window.close()};
}
test('all nine screens render without exception',()=>{const t=boot();assert.equal(t.$('#nav').children.length,9);for(const p of ['attendance','students','fees','crm','absence','messages','reports','settings','dashboard']){t.click(`[data-page="${p}"]`);assert.ok(t.$('#view').textContent.length>20);}t.close();});
test('registration, edit and persisted reload',()=>{const t=boot();t.student();assert.equal(t.state().students.length,1);t.click('[data-page="students"]');t.click('[data-action="editStudent"]');t.set('[name="name"]','가상학생수정');t.submit('#studentForm');const reload=boot(JSON.stringify(t.state()));reload.click('[data-page="students"]');assert.match(reload.$('#view').textContent,/가상학생수정/);reload.close();t.close();});
test('attendance record, correction, undo and natural command',()=>{const t=boot();t.student();t.click('[data-page="attendance"]');t.click('[data-status="absent"]');assert.equal(t.state().attendance[0].status,'absent');t.click('[data-status="late"]');assert.equal(t.state().attendance.length,1);assert.equal(t.state().attendance[0].status,'late');t.click('[data-action="unmark"]');assert.equal(t.state().attendance.length,0);t.set('#commandInput','가상수련생 출석 처리');t.click('#runCommandBtn');assert.equal(t.state().attendance[0].status,'present');t.close();});
test('monthly bills idempotent, partial payment, fee draft',()=>{const t=boot();t.student();t.click('[data-page="fees"]');t.click('[data-action="bill"]');t.click('[data-action="bill"]');assert.equal(t.state().payments.length,1);t.click('[data-action="editPayment"]');t.set('#editorForm [name="paid"]','50000');t.submit('#editorForm');assert.equal(t.state().payments[0].paid,50000);assert.match(t.$('#view').textContent,/100,000원/);t.click('[data-action="feeDraft"]');assert.equal(t.state().drafts[0].status,'draft');assert.match(t.state().drafts[0].text,/100,000원/);t.close();});
test('overpayment fails atomically',()=>{const t=boot();t.student();t.click('[data-page="fees"]');t.click('[data-action="bill"]');t.click('[data-action="editPayment"]');t.set('#editorForm [name="paid"]','999999');t.submit('#editorForm');assert.equal(t.state().payments[0].paid,0);assert.match(t.$('#assistantAnswer').textContent,/저장하지 못했습니다/);t.close();});
test('CRM conversion retains consultation and creates student',()=>{const t=boot();t.click('[data-page="crm"]');t.click('[data-action="addLead"]');t.set('#editorForm [name="name"]','가상상담자');t.submit('#editorForm');assert.equal(t.state().leads.length,1);t.click('[data-action="convertLead"]');t.submit('#studentForm');assert.equal(t.state().students[0].name,'가상상담자');assert.equal(t.state().leads[0].stage,'등록완료');t.close();});
test('message drafts can be edited and remain unsent',()=>{const t=boot();t.student();t.click('[data-page="messages"]');t.set('#draftForm [name="studentId"]',t.state().students[0].id);t.submit('#draftForm');t.set('[data-draft]','가상 테스트 초안');t.click('[data-action="saveDraft"]');assert.equal(t.state().drafts[0].text,'가상 테스트 초안');assert.equal(t.state().drafts[0].status,'draft');t.close();});
test('HTML injection in name is rendered as text',()=>{const t=boot();t.student('<img src=x onerror=alert(1)>');t.click('[data-page="students"]');assert.equal(t.$('#view img'),null);assert.match(t.$('#view').textContent,/<img/);t.close();});
test('corrupt storage is preserved and not overwritten',()=>{const t=boot('{broken');t.student();assert.equal(t.w.localStorage.getItem('dojang-os:v1'),'{broken');assert.match(t.$('#assistantAnswer').textContent,/오류/);t.close();});
test('storage quota failure leaves prior state intact',()=>{const t=boot();t.student();const original=t.w.localStorage.getItem('dojang-os:v1');t.w.Storage.prototype.setItem=()=>{throw new Error('QuotaExceededError');};t.click('[data-page="attendance"]');t.click('[data-status="present"]');assert.equal(t.w.localStorage.getItem('dojang-os:v1'),original);assert.match(t.$('#assistantAnswer').textContent,/QuotaExceeded/);t.close();});
test('another tab update stops stale writes',()=>{const t=boot();t.student();t.w.dispatchEvent(new t.w.StorageEvent('storage',{key:'dojang-os:v1'}));t.click('[data-page="attendance"]');t.click('[data-status="present"]');assert.equal(t.state().attendance.length,0);assert.match(t.$('#assistantAnswer').textContent,/다른 탭/);t.close();});
test('all report periods and settings persist',()=>{const t=boot();t.click('[data-page="settings"]');t.set('#settingsForm [name="name"]','가상도장');t.set('[name="absenceDays"]','10');t.submit('#settingsForm');assert.equal(t.state().settings.absenceDays,10);t.click('[data-page="reports"]');for(const kind of ['day','week','month']){t.change('[name="reportKind"]',kind);assert.match(t.$('.report').textContent,/가상도장/);}t.close();});
test('backup preview, restore, pre-restore snapshot, invalid rejection',async()=>{const t=boot();t.student();const original=JSON.stringify(t.state());t.click('[data-page="settings"]');const candidate=t.state();candidate.students[0].name='복원용가상학생';let input=t.$('#restoreFile');Object.defineProperty(input,'files',{value:[{size:1000,text:async()=>JSON.stringify(candidate)}],configurable:true});input.dispatchEvent(new t.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));assert.match(t.$('#restorePreview').textContent,/수련생 1명/);t.click('[data-action="restore"]');assert.equal(t.state().students[0].name,'복원용가상학생');assert.equal(t.w.localStorage.getItem('dojang-os:v1:before-restore'),original);input=t.$('#restoreFile');Object.defineProperty(input,'files',{value:[{size:20,text:async()=>'{bad'}],configurable:true});input.dispatchEvent(new t.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));assert.equal(t.$('[data-action="restore"]'),null);assert.equal(t.state().students[0].name,'복원용가상학생');t.close();});
