/* No analytics, external APIs, message sending, or payment execution. */
'use strict';
const C=window.Dojang, KEY='dojang-os:v1', PREVIOUS=KEY+':before-restore';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const won=n=>new Intl.NumberFormat('ko-KR').format(n)+'원';
const labels={present:'출석',late:'지각',absent:'결석',excused:'공결'};
const pages={dashboard:'운영 대시보드',attendance:'출석 관리',students:'수련생 관리',fees:'회비 관리',crm:'상담 CRM',absence:'장기결석',messages:'학부모 메시지',reports:'운영 리포트',settings:'설정 · 백업'};
let state=C.empty(),locked=false,page='dashboard',date=C.today(),month=date.slice(0,7),filter='',search='',reportKind='day',pendingRestore=null,editStudent=null,todayOnly=false;
try {const raw=localStorage.getItem(KEY);if(raw) state=C.validate(JSON.parse(raw));} catch(e){locked=true;}
function answer(text){$('#assistantAnswer').textContent=text;}
function transact(fn){
  if(locked){answer('저장 데이터 오류 또는 다른 탭 변경이 감지되었습니다. 설정에서 원본을 백업하고 복원하거나 새로고침하세요.');return false;}
  try{const next=structuredClone(state);fn(next);C.validate(next);localStorage.setItem(KEY,JSON.stringify(next));state=next;render();return true;}catch(e){answer('저장하지 못했습니다: '+e.message);return false;}
}
window.addEventListener('storage',e=>{if(e.key===KEY){locked=true;answer('다른 탭에서 데이터가 변경되었습니다. 새로고침 후 계속하세요.');}});
const button=(text,action,id='',cls='ghost')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${esc(text)}</button>`;
const panel=(title,body)=>`<section class="panel"><h3>${title}</h3>${body}</section>`;
const empty=text=>`<p class="empty">${text}</p>`;
const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const input=(label,name,type,value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
function go(p){page=p;search='';filter='';todayOnly=false;render();}
function studentName(id){return state.students.find(s=>s.id===id)?.name||'알 수 없음';}
function attendance(){
 const pupils=state.students.filter(s=>s.status==='active'&&s.joined<=date&&s.name.includes(search));
 const rows=pupils.filter(s=>!filter||state.attendance.find(a=>a.studentId===s.id&&a.date===date)?.status===filter).map(s=>{const a=state.attendance.find(a=>a.studentId===s.id&&a.date===date);return `<tr><td><b>${esc(s.name)}</b><div class="muted small">${esc(s.group)} · ${C.eligible(s,date)?'수업일':'비수업일'}</div></td><td><span class="tag">${a?labels[a.status]:'미체크'}</span></td><td><div class="status-row">${C.statuses.map(status=>`<button class="chip ${a?.status===status?'on '+status:''}" data-action="mark" data-id="${s.id}" data-status="${status}" aria-label="${esc(s.name)} ${labels[status]}">${labels[status]}</button>`).join('')}${a?button('취소','unmark',s.id,'chip'):''}</div></td></tr>`;});
 return panel('날짜별 출석',`<div class="toolbar">${input('기록일','date','date',date,`max="${C.today()}"`)}${input('이름 검색','search','search',search)}<label>상태<select aria-label="상태" name="filter"><option value="">전체</option>${C.statuses.map(s=>`<option value="${s}" ${filter===s?'selected':''}>${labels[s]}</option>`).join('')}</select></label>${button('수업 대상 전체 출석','all')}</div><p class="muted small">미체크는 결석으로 계산하지 않습니다. 전체 출석은 해당 요일 수업 대상 중 미체크만 기록합니다.</p>${rows.length?table(['수련생','상태','출석 기록'],rows):empty('등록된 수련생 또는 조건에 맞는 기록이 없습니다.')}`);
}
function students(){return panel('수련생 명단',`<div class="toolbar">${input('이름 검색','search','search',search)}</div>${state.students.length?table(['수련생','상태 / 회비','관리'],state.students.filter(s=>s.name.includes(search)).map(s=>`<tr><td><b>${esc(s.name)}</b><div class="muted">${esc(s.group)}</div><div>${esc(s.guardian)} ${esc(s.phone)}</div></td><td>${{active:'재원',paused:'휴원',left:'퇴원'}[s.status]} · ${won(s.fee)}<div class="muted small">등록 ${s.joined}</div></td><td>${button('수정','editStudent',s.id)}</td></tr>`)):empty('수련생 추가 버튼으로 첫 수련생을 등록하세요.')}`);}
function fees(){const bills=state.payments.filter(p=>p.month===month);return panel('월별 회비 장부',`<div class="toolbar">${input('청구 월','month','month',month)}${button('재원생 청구 생성','bill')}</div><p class="muted small">청구 생성은 장부 기록입니다. 실제 결제는 실행되지 않습니다. 기존 청구는 덮어쓰지 않습니다.</p><div class="summary">청구 ${won(bills.reduce((n,p)=>n+p.due,0))} · 수납 ${won(bills.reduce((n,p)=>n+p.paid,0))} · 미납 ${won(bills.reduce((n,p)=>n+p.due-p.paid,0))}</div>${bills.length?table(['수련생','청구 / 수납 / 미납','관리'],bills.map(p=>`<tr><td>${esc(studentName(p.studentId))}</td><td>${won(p.due)} / ${won(p.paid)}<div class="${p.due>p.paid?'kpi-warning':'kpi-positive'}">잔액 ${won(p.due-p.paid)}</div></td><td>${button('장부 수정','editPayment',p.id)}${p.due>p.paid?button('안내 초안','feeDraft',p.id):''}</td></tr>`)):empty('이 달의 청구가 없습니다. 청구 생성을 눌러 시작하세요.')}`);}
function crm(){const rows=state.leads.filter(l=>!todayOnly||l.next===C.today()).sort((a,b)=>(a.next||'9999').localeCompare(b.next||'9999'));return panel('상담 파이프라인',`<div class="toolbar">${button('+ 상담 등록','addLead')}${button(todayOnly?'전체 상담 보기':'오늘 상담만 보기','toggleToday')}</div>${rows.length?table(['상담자','단계 / 다음 일정','관리'],rows.map(l=>`<tr><td>${esc(l.name)}<div class="muted small">${esc(l.phone)}</div><div class="wrap">${esc(l.note)}</div></td><td><span class="tag">${esc(l.stage)}</span><div>${l.next||'일정 없음'}</div></td><td>${button('수정','editLead',l.id)}${l.stage!=='등록완료'?button('수련생 등록','convertLead',l.id):''}</td></tr>`)):empty('예정된 상담이 없습니다.')}`);}
function absence(){const rows=C.absences(state);return panel('장기결석 확인',`<p class="muted">출석·지각·공결 이후 ${state.settings.absenceDays}일 이상 경과하고 명시적 결석 기록이 있는 재원생입니다. 공결은 연속 결석을 끊습니다.</p>${rows.length?table(['수련생','마지막 기준일 / 결석 기록','관리'],rows.map(s=>`<tr><td>${esc(s.name)} · ${esc(s.group)}</td><td>${s.since} · ${s.gap}일 경과<div>결석 기록 ${s.missed}회</div></td><td>${button('안부 초안','absenceDraft',s.id)}</td></tr>`)):empty('현재 장기결석 대상이 없습니다.')}`);}
function messages(){return panel('초안 보관함',`<form id="draftForm" class="toolbar"><label>수련생<select aria-label="수련생" name="studentId" required><option value="">선택</option>${state.students.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.group)}</option>`).join('')}</select></label><label>종류<select aria-label="종류" name="kind"><option value="feedback">수업 피드백</option><option value="absence">결석 안부</option><option value="notice">공지</option></select></label><button class="primary">초안 만들기</button></form><p class="muted small">초안은 수정·복사만 가능합니다. 사실관계와 수신 대상을 확인한 뒤 별도로 사용하세요.</p><div class="list">${state.drafts.slice().reverse().map(m=>`<article class="item"><strong>${esc(studentName(m.studentId))} · ${esc(m.kind)} <span class="tag">초안</span></strong><p class="muted small">${m.created}</p><textarea aria-label="${esc(studentName(m.studentId))} 메시지 초안" data-draft="${m.id}" rows="5">${esc(m.text)}</textarea><div class="toolbar">${button('수정 저장','saveDraft',m.id)}${button('복사','copyDraft',m.id)}</div></article>`).join('')||empty('생성된 메시지 초안이 없습니다.')}</div>`);}
function reportText(kind=reportKind){const r=C.report(state,kind,date);return `${state.settings.name} · ${{day:'일일',week:'주간',month:'월간'}[kind]} 운영 리포트\n${r.start} ~ ${r.end}\n\n출석 ${r.counts.present}건 / 지각 ${r.counts.late}건 / 결석 ${r.counts.absent}건 / 공결 ${r.counts.excused}건\n기록 기준 출석률 ${r.rate===null?'계산할 기록 없음':r.rate+'%'}\n※ (출석+지각) ÷ (출석+지각+결석). 미체크·공결 제외.\n\n신규 수련생 ${r.registered}명 / 신규 상담 ${r.leads}건\n해당 월 청구 ${won(r.due)} / 누적 수납 ${won(r.paid)} / 미납 ${won(r.due-r.paid)}\n※ 회비는 청구 월의 현재 장부 잔액이며 기간 중 현금흐름이 아닙니다.\n\n현재 장기결석 대상 ${C.absences(state).length}명\n메시지 보관 ${state.drafts.length}건 (모두 미발송 초안)\n\n이 리포트는 현재 브라우저에 저장된 기록으로 생성되었습니다.`;}
function reports(){return panel('일 · 주 · 월 리포트',`<div class="toolbar"><label>기간<select aria-label="기간" name="reportKind">${[['day','일일'],['week','주간'],['month','월간']].map(([v,t])=>`<option value="${v}" ${reportKind===v?'selected':''}>${t}</option>`).join('')}</select></label>${input('기준일','date','date',date)}${button('리포트 복사','copyReport')}${button('텍스트 다운로드','downloadReport')}</div><pre class="report">${esc(reportText())}</pre>`);}
function settings(){return panel('도장 설정과 데이터 백업',`<p class="muted">데이터는 이 브라우저에만 저장됩니다. 기기 간 동기화·로그인은 없으며 브라우저 데이터 삭제 시 사라질 수 있습니다. 공용 기기에는 실제 개인정보를 입력하지 마세요.</p><form id="settingsForm" class="toolbar">${input('도장 이름','name','text',state.settings.name,'required maxlength="100"')}${input('장기결석 기준 일수','absenceDays','number',state.settings.absenceDays,'min="1" max="365" required')}<button class="primary">설정 저장</button></form><div class="toolbar">${button('전체 JSON 백업','backup')}${button('복원 전 사본 다운로드','previous')}</div><label>JSON 백업 선택 (최대 5MB)<input type="file" id="restoreFile" accept=".json,application/json"></label><div id="restorePreview"></div><p class="muted small">복원은 현재 자료를 교체합니다. 미리보기 후 직접 적용하며 기존 원본을 별도 보관합니다. 백업에는 개인정보가 포함될 수 있으니 안전하게 보관하세요.</p>${locked?'<p role="alert">기존 저장 데이터에 문제가 있거나 다른 탭 변경이 있습니다. 백업 후 검증된 파일로 복원하거나 새로고침하세요.</p>':''}`);}
function dashboard(){const r=C.report(state,'day',C.today()),active=state.students.filter(s=>s.status==='active'),due=state.payments.reduce((n,p)=>n+p.due-p.paid,0);return `<div class="metrics">${[['재원 수련생',active.length+'명'],['오늘 출석·지각',r.counts.present+r.counts.late+'명'],['누적 미납',won(due)],['장기결석',C.absences(state).length+'명']].map(([k,v])=>`<div class="panel metric"><div class="k">${k}</div><div class="v">${v}</div></div>`).join('')}</div><div class="grid-2">${panel('오늘 할 일',`<div class="list"><div class="item">${C.today()} · 수업 대상 ${active.filter(s=>C.eligible(s,C.today())).length}명</div><div class="item">오늘 상담 ${state.leads.filter(l=>l.next===C.today()).length}건</div><div class="item">메시지 초안 ${state.drafts.length}건 · 발송 기능 없음</div></div>`)}${panel('운영 시작',`<p class="muted">수련생을 등록하고 요일을 설정하면 출석과 회비 장부를 함께 관리할 수 있습니다.</p>${button('출석 확인','gotoAttendance')}${button('백업 관리','gotoSettings')}`)}</div>`;}
function render(){
 $('#nav').innerHTML=Object.entries(pages).map(([k,v])=>`<button class="nav-btn ${page===k?'active':''}" data-page="${k}" ${page===k?'aria-current="page"':''}>${v}</button>`).join('');
 $('#pageTitle').textContent=pages[page];$('#pageSub').textContent=state.settings.name+' · '+C.today()+' · 로컬 저장';
 $('#view').innerHTML=({dashboard,attendance,students,fees,crm,absence,messages,reports,settings}[page])();
}
function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copy(text){try{await navigator.clipboard.writeText(text);answer('복사했습니다.');}catch(e){answer('복사가 허용되지 않았습니다. 텍스트를 직접 선택해 복사하세요.');}}
function backup(){try{download(localStorage.getItem(KEY)||JSON.stringify(state,null,2),'dojang-backup-'+C.today()+'.json');}catch(e){answer(e.message);}}
const modal=document.createElement('dialog');modal.id='editorDialog';document.body.append(modal);
function openEditor(title,fields,onSave){modal.innerHTML=`<form id="editorForm"><div class="dialog-head"><h3>${title}</h3><button type="button" class="icon-btn" data-close>✕</button></div>${fields}<menu><button type="button" class="ghost" data-close>취소</button><button class="primary">저장</button></menu></form>`;modal.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal.close());modal.querySelector('form').onsubmit=e=>{e.preventDefault();if(onSave(new FormData(e.target)))modal.close();};modal.showModal();}
function studentEditor(id=null,leadId=null){const s=state.students.find(s=>s.id===id),l=state.leads.find(l=>l.id===leadId);editStudent=id;const form=$('#studentForm');form.reset();form.elements.name.value=s?.name||l?.name||'';form.elements.group.value=s?.group||'초등부';form.elements.fee.value=s?.fee??150000;form.elements.memo.value=s?.memo||'';
 $('#studentExtra').innerHTML=`${input('보호자 이름 (선택)','guardian','text',s?.guardian||'','maxlength="100"')}${input('연락처 (선택)','phone','tel',s?.phone||l?.phone||'','maxlength="40"')}${input('등록일','joined','date',s?.joined||C.today(),'required')}<label>재원 상태<select aria-label="재원 상태" name="status">${[['active','재원'],['paused','휴원'],['left','퇴원']].map(([v,t])=>`<option value="${v}" ${s?.status===v?'selected':''}>${t}</option>`).join('')}</select></label><fieldset><legend>수업 요일</legend><div class="weekdays">${['일','월','화','수','목','금','토'].map((n,i)=>`<label><input type="checkbox" name="schedule" value="${i}" ${(s?.schedule||[1,2,3,4,5]).includes(i)?'checked':''}>${n}</label>`).join('')}</div></fieldset>`;
 form.dataset.lead=leadId||'';$('#studentDialog').showModal();}
const extra=document.createElement('div');extra.id='studentExtra';$('#studentForm menu').before(extra);$('#studentForm').removeAttribute('method');$('#studentForm [name="name"]').maxLength=100;$('#studentForm [name="memo"]').maxLength=5000;$('#studentForm [name="fee"]').required=true;$('#studentForm [name="fee"]').max=100000000;$('#studentForm [name="fee"]').step=1;
$('#studentForm').querySelectorAll('[value="cancel"]').forEach(b=>{b.type='button';b.onclick=()=>$('#studentDialog').close();});
$('#studentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name').trim(),schedule=f.getAll('schedule').map(Number);if(!name||!schedule.length){answer('이름과 수업 요일을 입력하세요.');return;}
 const data={id:editStudent||C.id(),name,group:f.get('group'),fee:Number(f.get('fee')),memo:f.get('memo'),guardian:f.get('guardian'),phone:f.get('phone'),joined:f.get('joined'),status:f.get('status'),schedule};
 if(state.attendance.some(a=>a.studentId===data.id&&a.date<data.joined)){answer('출석 기록보다 등록일을 뒤로 변경할 수 없습니다.');return;}
 if(transact(d=>{const idx=d.students.findIndex(s=>s.id===data.id);if(idx<0)d.students.push(data);else d.students[idx]=data;const lead=d.leads.find(l=>l.id===e.target.dataset.lead);if(lead)lead.stage='등록완료';})){$('#studentDialog').close();answer('수련생 정보를 저장했습니다.');}};
function leadEditor(id){const l=state.leads.find(l=>l.id===id);openEditor(l?'상담 수정':'상담 등록',`${input('이름','name','text',l?.name||'','required maxlength="100"')}${input('연락처 (선택)','phone','tel',l?.phone||'','maxlength="40"')}<label>단계<select aria-label="단계" name="stage">${C.stages.map(s=>`<option ${l?.stage===s?'selected':''}>${s}</option>`).join('')}</select></label>${input('다음 일정','next','date',l?.next||'')}<label>상담 메모<textarea name="note" maxlength="5000">${esc(l?.note||'')}</textarea></label>`,f=>transact(d=>{const value={id:id||C.id(),name:f.get('name').trim(),phone:f.get('phone'),stage:f.get('stage'),next:f.get('next'),note:f.get('note'),created:l?.created||C.today()};const idx=d.leads.findIndex(x=>x.id===id);if(idx<0)d.leads.push(value);else d.leads[idx]=value;}));}
function paymentEditor(id){const p=state.payments.find(p=>p.id===id);openEditor('수납 장부 수정 (실제 결제 아님)',`${input('청구액','due','number',p.due,'required min="0" max="100000000" step="1"')}${input('누적 수납액','paid','number',p.paid,'required min="0" max="100000000" step="1"')}${input('수납일 (선택)','paidAt','date',p.paidAt)}<label>메모<textarea name="note" maxlength="5000">${esc(p.note)}</textarea></label>`,f=>transact(d=>Object.assign(d.payments.find(x=>x.id===id),{due:Number(f.get('due')),paid:Number(f.get('paid')),paidAt:f.get('paidAt'),note:f.get('note')})));}
function draft(studentId,kind,payment=null){const s=state.students.find(s=>s.id===studentId);if(!s)return;const head=`안녕하세요, ${s.name} 보호자님. ${state.settings.name}입니다. `;const body=kind==='fee'?`${payment.month} 회비 장부상 잔액은 ${won(payment.due-payment.paid)}입니다. 이미 납부하셨다면 확인을 위해 알려주세요. 감사합니다.`:kind==='absence'?'최근 수련 참여가 어려운 사정이 있으신지 안부 여쭙습니다. 편하실 때 아이의 근황을 알려주세요. 즐겁게 복귀할 수 있도록 돕겠습니다.':kind==='notice'?'[공지 제목]\n[일시와 내용을 확인해 입력하세요.]\n궁금하신 점은 도장으로 문의해 주세요.':'오늘 [수업 내용]을 함께 연습했습니다. [직접 관찰한 노력과 성장]을 칭찬해 주세요. 감사합니다.';
 if(transact(d=>d.drafts.push({id:C.id(),studentId,kind:{fee:'회비 안내',absence:'결석 안부',notice:'공지',feedback:'수업 피드백'}[kind],text:head+body,created:C.today(),status:'draft'}))){go('messages');answer('메시지 초안을 저장했습니다. 발송되지 않았습니다.');}}
function markAll(day){const ids=state.students.filter(s=>C.eligible(s,day)&&!state.attendance.some(a=>a.studentId===s.id&&a.date===day)).map(s=>s.id);if(!ids.length){answer('미체크 수업 대상이 없습니다.');return;}if(confirm(`${day} 수업 대상 중 미체크 ${ids.length}명을 출석 처리할까요?`))transact(d=>ids.forEach(id=>C.mark(d,id,day,'present')));}
function showReport(kind='day'){date=C.today();$('#reportText').textContent=reportText(kind);$('#reportDialog h3').textContent='운영 리포트';$('#reportDialog').showModal();}
function run(){const result=C.command(state,$('#commandInput').value);if(result.type==='answer')answer(result.text);else if(result.type==='navigate'){page=result.page;date=C.today();month=date.slice(0,7);search='';filter=result.filter||'';todayOnly=!!result.todayOnly;render();answer(pages[page]+' 화면에서 현재 기록을 확인하세요.');}else if(result.type==='mark'){if(transact(d=>C.mark(d,result.studentId,result.date,result.status)))answer(studentName(result.studentId)+' '+labels[result.status]+' 기록 완료');}else if(result.type==='markAll')markAll(result.date);else if(result.type==='report'){reportKind=result.kind;date=C.today();go('reports');}}
$('#addStudentBtn').onclick=()=>studentEditor();$('#quickReportBtn').onclick=()=>showReport();$('#runCommandBtn').onclick=run;$('#commandInput').setAttribute('aria-label','자연어 운영 명령');$('#assistantAnswer').setAttribute('role','status');$('.command-label').textContent='자연어 명령 · 로컬 규칙 기반';$('#commandInput').onkeydown=e=>{if(e.key==='Enter')run();};$('#closeReportBtn').onclick=()=>$('#reportDialog').close();$('#copyReportBtn').onclick=()=>copy($('#reportText').textContent);$('#exportBackupBtn').onclick=backup;
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){go(b.dataset.page);return;}if(b.dataset.cmd){$('#commandInput').value=b.dataset.cmd;run();return;}const id=b.dataset.id;
 switch(b.dataset.action){
 case 'gotoAttendance':go('attendance');break;case 'gotoSettings':go('settings');break;
 case 'mark':transact(d=>C.mark(d,id,date,b.dataset.status));break;
 case 'unmark':transact(d=>{d.attendance=d.attendance.filter(a=>!(a.studentId===id&&a.date===date));});break;
 case 'all':markAll(date);break;case 'editStudent':studentEditor(id);break;
 case 'bill':{const targets=state.students.filter(s=>s.status==='active'&&s.joined.slice(0,7)<=month&&!state.payments.some(p=>p.studentId===s.id&&p.month===month));if(!targets.length){answer('새로 청구할 재원생이 없습니다.');break;}if(confirm(`${month} 회비 ${targets.length}건을 장부에 생성할까요?`))transact(d=>targets.forEach(s=>d.payments.push({id:C.id(),studentId:s.id,month,due:s.fee,paid:0,paidAt:'',note:''})));break;}
 case 'editPayment':paymentEditor(id);break;case 'feeDraft':{const p=state.payments.find(p=>p.id===id);draft(p.studentId,'fee',p);break;}
 case 'addLead':leadEditor();break;case 'editLead':leadEditor(id);break;case 'convertLead':studentEditor(null,id);break;case 'toggleToday':todayOnly=!todayOnly;render();break;
 case 'absenceDraft':draft(id,'absence');break;
 case 'saveDraft':{const text=$(`[data-draft="${id}"]`).value;if(transact(d=>{d.drafts.find(m=>m.id===id).text=text;}))answer('초안 수정 저장 완료');break;}
 case 'copyDraft':copy($(`[data-draft="${id}"]`).value);break;
 case 'copyReport':copy(reportText());break;case 'downloadReport':download(reportText(),'dojang-report-'+date+'.txt','text/plain');break;
 case 'backup':backup();break;case 'previous':{const raw=localStorage.getItem(PREVIOUS);raw?download(raw,'dojang-before-restore.json'):answer('복원 전 사본이 없습니다.');break;}
 case 'restore':if(pendingRestore&&confirm('현재 데이터를 선택한 백업으로 교체할까요? 현재 원본은 복원 전 사본으로 보관됩니다.')){try{const next=C.validate(pendingRestore);localStorage.setItem(PREVIOUS,localStorage.getItem(KEY)||JSON.stringify(state));localStorage.setItem(KEY,JSON.stringify(next));state=next;locked=false;pendingRestore=null;render();answer('복원을 완료했습니다. 복원 전 사본을 다운로드할 수 있습니다.');}catch(e){answer('복원 실패: '+e.message);}}break;
 }
});
document.addEventListener('change',async e=>{const el=e.target;if(el.id==='restoreFile'){pendingRestore=null;$('#restorePreview').textContent='';const file=el.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw new Error('5MB 이하 파일만 복원할 수 있습니다.');const candidate=C.validate(JSON.parse(await file.text()));pendingRestore=candidate;$('#restorePreview').innerHTML=`<p>수련생 ${candidate.students.length}명 · 출석 ${candidate.attendance.length}건 · 청구 ${candidate.payments.length}건 · 상담 ${candidate.leads.length}건 · 초안 ${candidate.drafts.length}건</p>${button('확인 후 복원 적용','restore')}`;}catch(e){answer(e.message);$('#restorePreview').textContent='복원할 수 없는 파일입니다.';}return;}
 if(!el.closest('#view')||el.closest('form'))return;
 if(el.name==='date'&&C.validDate(el.value)){date=el.value;render();}if(el.name==='month'&&/^\d{4}-(0[1-9]|1[0-2])$/.test(el.value)){month=el.value;render();}if(el.name==='filter'){filter=el.value;render();}if(el.name==='reportKind'){reportKind=el.value;render();}if(el.name==='search'){search=el.value;render();}
});
document.addEventListener('submit',e=>{if(e.target.id==='settingsForm'){e.preventDefault();const f=new FormData(e.target);transact(d=>{d.settings={name:f.get('name').trim(),absenceDays:Number(f.get('absenceDays'))};});}if(e.target.id==='draftForm'){e.preventDefault();const f=new FormData(e.target);draft(f.get('studentId'),f.get('kind'));}});
render();if(locked)answer('保存된 데이터가 올바르지 않습니다. 원본을 보존했습니다. 설정에서 백업 후 복원하세요.'.replace('保存','저장'));
